# Generated by Django 4.1.7 on 2023-03-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='task',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
