# Generated by Django 4.1.7 on 2023-03-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_usuproyrol_usuario_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(choices=[('scrum_master', 'Scrum Master'), ('product_owner', 'Product Owner'), ('team_member', 'Team Member')], max_length=500),
        ),
    ]
