# Generated by Django 4.1.7 on 2023-04-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_rol_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
