# Generated by Django 4.1.7 on 2023-05-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_sprint_fecha_fin_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='definicion_hecho',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estados',
            name='estado',
            field=models.CharField(choices=[('hacer', 'Por hacer'), ('proceso', 'En proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], max_length=10),
        ),
    ]
